version: '3'
services:
  #MySQL Service
  db-temp:
    image: mysql
    container_name: db_sharing
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_PASSWORD: 'welcome1'
      MYSQL_ROOT_PASSWORD: 'welcome1'
    volumes:
      - ./mysql-data:/var/lib/mysql
volumes:
  mysql-data:
